# fly.toml app configuration file generated for osc-api-rest-prod on 2026-06-22T14:37:27Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'osc-api-rest-prod'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
